from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from datetime import datetime

db = SQLAlchemy()

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(120), nullable=False)
    role = db.Column(db.String(20), nullable=False)  # 'doctor', 'dean', 'chairman', 'patient'
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    patients = db.relationship('Patient', backref='doctor', lazy=True, foreign_keys='Patient.doctor_id')
    patient_records = db.relationship('Patient', backref='patient_user', lazy=True, foreign_keys='Patient.patient_user_id')

class Patient(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    gender = db.Column(db.String(10), nullable=False)
    age = db.Column(db.Integer, nullable=False)
    chest_pain = db.Column(db.Boolean, default=False)
    shortness_of_breath = db.Column(db.Boolean, default=False)
    fatigue = db.Column(db.Boolean, default=False)
    systolic = db.Column(db.Integer, nullable=False)
    diastolic = db.Column(db.Integer, nullable=False)
    heart_rate = db.Column(db.Integer, nullable=False)
    lung_sounds = db.Column(db.Boolean, default=False)
    cholesterol = db.Column(db.Integer, nullable=False)
    ldl = db.Column(db.Integer, nullable=False)
    hdl = db.Column(db.Integer, nullable=False)
    diabetes = db.Column(db.Boolean, default=False)
    atrial_fibrillation = db.Column(db.Boolean, default=False)
    rheumatic_fever = db.Column(db.Boolean, default=False)
    mitral_stenosis = db.Column(db.Boolean, default=False)
    aortic_stenosis = db.Column(db.Boolean, default=False)
    tricuspid_stenosis = db.Column(db.Boolean, default=False)
    pulmonary_stenosis = db.Column(db.Boolean, default=False)
    dilated_cardiomyopathy = db.Column(db.Boolean, default=False)
    hypertrophic_cardiomyopathy = db.Column(db.Boolean, default=False)
    drug_use = db.Column(db.Boolean, default=False)
    fever = db.Column(db.Boolean, default=False)
    chills = db.Column(db.Boolean, default=False)
    alcoholism = db.Column(db.Boolean, default=False)
    hypertension = db.Column(db.Boolean, default=False)
    fainting = db.Column(db.Boolean, default=False)
    dizziness = db.Column(db.Boolean, default=False)
    smoking = db.Column(db.Boolean, default=False)
    obesity = db.Column(db.Boolean, default=False)
    murmur = db.Column(db.Boolean, default=False)
    prediction_result = db.Column(db.String(100), nullable=False)
    doctor_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    patient_user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=True)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow) 